<?php
// print_report.php
include("connection.php");
include('session.php');
requireRole('admin');

// 1. GET DATA FROM URL
$startDate = $_GET['start_date'] ?? date('Y-m-01');
$endDate = $_GET['end_date'] ?? date('Y-m-d');
$statusFilter = $_GET['status'] ?? 'All';

// 2. QUERY
$sql = "SELECT * FROM shipments WHERE DATE(created_at) BETWEEN '$startDate' AND '$endDate'";
if($statusFilter != 'All') {
    $sql .= " AND status = '$statusFilter'";
}
$sql .= " ORDER BY created_at ASC";
$result = $conn->query($sql);

// 3. GENERATE REPORT DETAILS
$totalSales = 0;
$generatedBy = "Administrator"; // Pwede mong kunin sa session name mo
$dateGenerated = date('F j, Y h:i A');
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Official Report - Slate Freight</title>
    <style>
        body { font-family: 'Helvetica', Arial, sans-serif; font-size: 12px; color: #333; padding: 20px; }
        .header { text-align: center; margin-bottom: 30px; border-bottom: 2px solid #333; padding-bottom: 10px; }
        .logo { max-width: 150px; margin-bottom: 10px; }
        .company-name { font-size: 24px; font-weight: bold; text-transform: uppercase; margin: 0; }
        .report-title { font-size: 18px; font-weight: bold; margin-top: 5px; color: #555; }
        .meta-info { display: flex; justify-content: space-between; margin-bottom: 20px; font-size: 13px; }
        
        table { width: 100%; border-collapse: collapse; margin-bottom: 30px; }
        th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
        th { background-color: #f2f2f2; font-weight: bold; text-transform: uppercase; }
        .text-end { text-align: right; }
        .total-row { background-color: #eee; font-weight: bold; font-size: 14px; }
        
        .footer { margin-top: 50px; display: flex; justify-content: space-between; }
        .signature-line { border-top: 1px solid #333; width: 200px; padding-top: 5px; text-align: center; }
        
        /* Print Settings */
        @media print {
            .no-print { display: none; }
            body { padding: 0; }
            @page { margin: 20mm; }
        }
    </style>
</head>
<body onload="window.print()">

    <div class="no-print" style="margin-bottom: 20px;">
        <button onclick="window.close()" style="padding: 10px 20px; cursor: pointer;">Close Window</button>
        <button onclick="window.print()" style="padding: 10px 20px; cursor: pointer; font-weight: bold;">Print Again</button>
    </div>

    <div class="header">
        <img src="Remorig.png" alt="LOGO" class="logo" onerror="this.style.display='none'">
        <h1 class="company-name">Slate Freight Logistics</h1>
        <p>123 Logistics Road, Metro Manila, Philippines | (02) 8123-4567</p>
        <div class="report-title">
            <?php echo strtoupper($statusFilter); ?> SHIPMENT REPORT
        </div>
    </div>

    <div class="meta-info">
        <div>
            <strong>Reporting Period:</strong><br>
            <?php echo date('M d, Y', strtotime($startDate)); ?> to <?php echo date('M d, Y', strtotime($endDate)); ?>
        </div>
        <div class="text-end">
            <strong>Generated On:</strong> <?php echo $dateGenerated; ?><br>
            <strong>Generated By:</strong> <?php echo $generatedBy; ?>
        </div>
    </div>

    <table>
        <thead>
            <tr>
                <th>Tracking #</th>
                <th>Date</th>
                <th>Sender</th>
                <th>Receiver</th>
                <th>Dest. Island</th>
                <th>Status</th>
                <th class="text-end">Price</th>
            </tr>
        </thead>
        <tbody>
            <?php 
            if ($result->num_rows > 0):
                while($row = $result->fetch_assoc()): 
                    $totalSales += $row['price'];
            ?>
            <tr>
                <td><?php echo $row['id']; ?></td>
                <td><?php echo date('M d, Y', strtotime($row['created_at'])); ?></td>
                <td><?php echo $row['sender_name']; ?></td>
                <td><?php echo $row['receiver_name']; ?></td>
                <td><?php echo $row['destination_island']; ?></td>
                <td><?php echo $row['status']; ?></td>
                <td class="text-end">₱<?php echo number_format($row['price'], 2); ?></td>
            </tr>
            <?php endwhile; else: ?>
            <tr><td colspan="7" style="text-align:center; padding: 20px;">No records found.</td></tr>
            <?php endif; ?>
        </tbody>
        <tfoot>
            <tr class="total-row">
                <td colspan="6" class="text-end">GRAND TOTAL:</td>
                <td class="text-end">₱<?php echo number_format($totalSales, 2); ?></td>
            </tr>
        </tfoot>
    </table>

    <div class="footer">
        <div>
            <p>Certified Correct:</p>
            <br><br>
            <div class="signature-line">
                System Administrator
            </div>
        </div>
        <div>
            <p>Noted By:</p>
            <br><br>
            <div class="signature-line">
                Operations Manager
            </div>
        </div>
    </div>

    <div style="text-align: center; margin-top: 30px; font-size: 10px; color: #999;">
        This is a system-generated report. No signature required.
    </div>

</body>
</html>